### ISSUE TITLE
 Code as base for CalDAV client

### ISSUE THREAD

**Issue by IamSAB** [mstilkerich/carddavclient#15]
That is not really a feature request but more of a question or an effort estimate from you. 

As I understood, the CalDav and CardDav Clients use the same mechanism to CRUD und SYNC (both are extensions to the WebDAV protocol). I first thought, I could just use VCalendar instead of VCard in this client to update it to serve both. But taking a look, the VCard stuff is everywhere and not really seperated.

So my question is, how much effort it would take, to port this client to be compatible to handle iCalendar/CalDav? What classes or what part of them would one need to change? Or which ones are "general" enough to reuse them? Have you ever thought about such a project or received any feedbacks?

As far as I can tell, this library is the most extensive and well documented lib I found for CaldDAV. I already hoped to find the same quality for CalDAV, but there are just very "simple" clients available (no offering of sync or then just a php mess ...).

Glad to hear from you. Best,
Simon

**Comment by mstilkerich** [comment]
Hello,

 yes, I thought about supporting CalDAV as well when I created the lib. I decided against it back then simply because I have no need for it, but kept it as a possible future extension in mind. I still have no concrete plans for it, as I still lack personal need for it but also the free time to do it.

Extending the lib to support CalDAV as well concerning the currently supported feature set for CardDAV should not be that much work (I would expect a couple of days for the pure implementation part), but it is not as small an effort as you appear to expect. CardDAV and CalDAV use the same mechanisms, but if you look at it a bit closer you will find that there are many differences in the details beyond just the different formats of the actual data objects (calendar items vs address objects). So you will find counterparts for many operations in the two specs. One example:: The `addressbook-query` report and the `calendar-query` report to search an addressbook / calender for items matching certain criteria. Apart from their name, these reports also differ in the filter possibilities, particularly for a calendar there are filters concerning a time range (which of course makes no sense with CardDAV).

However, apart from the effort for implementation, there is the effort for documentation and tests, including interoperability with various CalDAV servers/services. Especially the tests easily exceed the effort of the plain implementation.

Then you would have a CalDAV client lib supporting discovery, sync, and basic operations on calendars. There is still more in the CalDAV protocol that could be supported, e.g. free/busy queries with the server. A client that syncs the complete calendars for offline use could do this offline, but a client without a local copy might have need for these features. 

So what parts of the classes would have to be adapted? I guess you have seen the [overview diagram](https://github.com/mstilkerich/carddavclient/tree/master/doc).

I would proceed as follows:
- Create a `CalendarCollection` as a sibling to `AddressbookCollection`. It doesn't have to support all the functions from the beginning, particularly the complex `query()` function but can be extended stepwise.
- The `CardDavClient` class (a poor name if it is extended beyond CardDAV) contains the basic operations at the WebDAV level, together with the XML serializers / deserializers in the XMLElements package. It would have to be extended as needed with the corresponding CalDAV WebDAV operations. The XML serializers / deserializers can probably be used without adaptations, but need to be extended for new CalDAV-specific XML elements.
- The Discovery service is the same for CalDAV, except that some aspects would have to become configurable (e.g. the SRV/TXT names, the addressbook-home-set vs calendar-home-set property), and of course the creation of the proper object type in the end.
- The Sync service is largely based on WebDAV mechanisms below CalDAV/CardDAV, except for the callback to the application SyncHandler that involves parsing the address objects (and then the calendar events, respectively), so most of this code could be reused as is as well.
- For the two services, it would probably make sense to factor out the common part into a superclass or trait, and have specializations for CardDAV and CalDAV. Applications normally will deal either with one or the other and should not face the increased complexity of the generalization unnecessarily.
