### ISSUE TITLE
 Exception: Expected Multistatus HTTP request was not successful (401 Unauthorized)

### ISSUE THREAD

**Issue by ericxuo** [mstilkerich/carddavclient#21]
Hi,

I've just installed RoundCube 1.6 and updated my carddav plugin to version v4.4.3.
And Nextcloud to version 24.0.4 as well (too much updates at the same time I guess).
I get the following error message when I display my nextcloud addressbook in RC : 

```
[15-Aug-2022 15:39:31 +0000]: <eblr3e4g> [5 ERR] Errors occurred during the refresh of addressbook 4: Exception: Expected Multistatus HTTP request was not successful (401 Unauthorized): <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:o="http://owncloud.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\PasswordLoginForbidden</s:exception>
  <s:message/>
  <o:hint xmlns:o="o:">password login forbidden</o:hint>
</d:error>

```
You will tell me I didn't provide the correct username/password but I think I did it correctly  (and it was working fine before these updates).
username : the one from NextCloud (nothing to deal with RC).
password : a new one created from the NC application as I use the TOTP Authentication when I connect to NC. This password is in the form 12345-abcde-...

Could you help me to solve that issue ?

Regards.

Xuo.

**Comment by mstilkerich** [comment]
Hello, I also have a Nextcloud 24.0.4 installation with TOTP authentication set up. I get the error message when I either use a wrong password or the account password, but it works fine with an app-specific password. From what you describe, you also use an app-specific password, so it seems you are doing everything right and it should work. However, other than asking you to double check I have no other clue what might cause this, since it works just fine for me.

I use the "Two-Factor TOTP Provider" app, version 6.4.0, just in case there is different apps for 2FA in Nextcloud.

**Comment by mstilkerich** [comment]
If you have double checked, you can enable HTTP debug logging in config.inc.php. You will also have to change the source code a bit to disable the redaction of the Authorisation header in the logs. For that, edit `plugins/carddav/src/Config.php` and change the line:

```php
        $this->httpLogger = new RoundcubeLogger("carddav_http", LogLevel::ERROR);
```

to 

```php
        $this->httpLogger = new RoundcubeLogger("carddav_http", LogLevel::ERROR, false);
```

Make sure you changed the line with the httpLogger, not the other logger.

Then you can try an operation interacting with the addressbook, e.g. force a resync. Then check the logs for the authorisation header. Then you can use `base64 --decode` and copy the string following the "Authorisation: Basic" to see if the password is properly passed to Nextcloud. If this all looks good, the issue is on the server side.

**Comment by mstilkerich** [comment]
One more idea: Do you use a password encryption scheme for carddav and did the key used for the encryption change? Depending on the scheme, the key is either the roundcube des_key (specific to the roundcube installation, but if you upgraded roundcube with a fresh install it might have changed) or your imap password. In such cases rcmcarddav cannot decrypt the password anymore and you could also see this error.

**Comment by ericxuo** [comment]
Hi,

Thank you for all these explanations. Currently, I've no time to work on this. I'll try to do all you proposed tomorrow (hopefully).
About your 3rd comment, I don't know if I use or not a password encryption scheme for carddav but what if the des_key has changed ? How to re-initialized the carddav decryption ?

Regards.

Xuo.

**Comment by mstilkerich** [comment]
The des_key is a setting in the roundcube config.inc.php. It is randomly generated on initial installation and should not change afterwards. If it did and you still have access to the previous config file, you can get the old des_key from there. Otherwise you would have to store the password for the addressbook via settings interface again and it will be encrypted with the new key.

Which pwstore_scheme is used is set in config.inc.php of the carddav plugin.

**Comment by ericxuo** [comment]
Hi,

1) I get the same version than you for the  Two-Factor TOTP Provider  in Nextcloud : 6.4.0
2) I've made the change in plugins/carddav/src/Config.php + replaced LogLevel::ERROR with LogLevel::DEBUG
    => The password used is (almost) the one from the application, not the app-specific one.
I've said "almost" because base64 --decode returned : 
xuo:<application password>
I don't know if "xuo" is expected (it is not part of the password).
But it looks like updating the password field in the carddav gui does not work.
3) In plugins/carddav/config.inc.php : // $prefs['_GLOBAL']['pwstore_scheme'] = 'base64';
    => The pwstore_scheme is commented out. I think base64 is used by default.
4) The des key is the same than in the previous RC version (1.5.2).

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

From the RC database, I can see : 
![ksnip_20220816-204011](https://user-images.githubusercontent.com/9089499/184954702-3efc4804-c354-46a3-9890-3f91f97a1585.png)
1) Why are there 3 passwords fields for the same user ?
2) Which one does carddav use ?
3) How to decode a password defined with "ENCRYPTED" and not "BASE64" ?

The last one is a trial I've made by removing the "443" port to see if it could change anything.
The 2 first ones seem to be exactly the same (except the user id) => I need to check which user id I am.

Regards.

Xuo.

**Comment by mstilkerich** [comment]
Hello,
  rcmcarddav v4 stores the addressbooks independently from one another. So if you nextcloud provides three addressbooks, all of them are stored with individual username and password. If you want to change the password you need to do so for all three addressbooks in the settings pane. I suggest you store the password newly for all three addressbooks. Then you should also not see a mix of pwstore schemes in the db.

Actually encrypted is the default scheme and users your imap password as encryption key.

The Authorization Basic header is supposed to decode to username:password.

**Comment by mstilkerich** [comment]
About the PHP error: This is actually a bug that I will fix, but I’m not sure it causes your auth trouble. However, you can edit the file named in the error message and change the line
```php
unset($this->authScheme);
```
to
```php
$this->authScheme = null;
```

and see if it makes a difference.

**Comment by ericxuo** [comment]
Hi,

From the carddav_http.log, the encryption used is BASE64. But you say, that it is ENCRYPTED by default.
There is something weird here, no ?
And is there a way to decrypt an ENCRYPTED password ?

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

It is working now but honestly, I don't know what I did, except removing the 2 passwords of the 2 other email addresses. And I think it was not useful because I'll need to re-create them to get access to the cardbook for my other email addresses.
Anyway, thank you for your help. If I understand the reason why it has suddenly starting to re-work, I'll post here.

Regards.

Xuo.
